In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_columns', None)

### Знакомство с данными

In [71]:
df_jobs = pd.read_csv('../data/ai_jobs_market_2025_2026.csv')
df_col = pd.read_csv('../data/world_cost_of_living_quality_of_life_2024_2025.csv')

In [72]:
df_jobs.head(3)

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,country,remote_work,company_size,industry,required_skills,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000.0,155000,290000,Boston,USA,On-site,Startup (1-50),Finance,APIs|Planning Systems|Python|Cloud|SQL|Leadership,13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2,Bachelor's,166000.0,90000,200000,London,UK,Hybrid,Enterprise (5000+),Finance,Python|Documentation|LLM APIs|Prompt Design|NL...,5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k)
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4,Associate's,360000.0,160000,300000,Seattle,USA,Fully Remote,Big Tech (FAANG+),Finance,Vector DBs|Python|Prompt Engineering|Fine-tuni...,9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k)

In [73]:
df_jobs.dtypes

job_id                       str
job_title                    str
job_category                 str
experience_level             str
years_of_experience        int64
education_required           str
annual_salary_usd        float64
salary_min_usd             int64
salary_max_usd             int64
city                         str
country                      str
remote_work                  str
company_size                 str
industry                     str
required_skills              str
ai_salary_premium_pct    float64
demand_score               int64
demand_growth_yoy_pct    float64
benefits_score_10        float64
posting_year               int64
posting_month              int64
is_senior                  int64
is_remote_friendly         int64
is_llm_role                int64
salary_tier                  str
dtype: object

In [74]:
print(f'Количество пропусков в датасете с вакансиями: {df_jobs.isnull().sum().sum()}')
print(f'Количество дубликатов в датасете с вакансиями: {df_jobs.duplicated().sum().sum()}')

Количество пропусков в датасете с вакансиями: 0
Количество дубликатов в датасете с вакансиями: 0

In [75]:
df_jobs.describe()

,years_of_experience,annual_salary_usd,salary_min_usd,salary_max_usd,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,6.216000,194892.000000,135448.666667,257537.333333,10.858200,87.523333,31.116333,7.897333,2025.584000,3.968000,0.496667,0.754000,0.218000
std,2.675216,66506.822013,24448.950878,39852.822207,4.029742,8.026315,22.046343,1.102846,0.493058,3.270388,0.500156,0.430822,0.413025
min,1.000000,90000.000000,90000.000000,180000.000000,3.000000,68.000000,5.000000,6.000000,2025.000000,1.000000,0.000000,0.000000,0.000000
25%,4.000000,144750.000000,120000.000000,218000.000000,8.200000,82.000000,15.375000,6.900000,2025.000000,2.000000,0.000000,1.000000,0.000000
50%,6.000000,180000.000000,140000.000000,270000.000000,10.500000,89.000000,23.400000,7.900000,2026.000000,3.000000,0.000000,1.000000,0.000000
75%,8.000000,236250.000000,155000.000000,290000.000000,14.200000,95.000000,42.700000,8.900000,2026.000000,5.000000,1.000000,1.000000,0.000000
max,15.000000,384000.000000,180000.000000,320000.000000,18.000000,98.000000,87.800000,9.800000,2026.000000,12.000000,1.000000,1.000000,1.000000

In [76]:
def get_outliers(df, column):

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    left = Q1 - 1.5 * IQR
    right = Q3 + 1.5 * IQR

    outliers = df[(df[column] < left) | (df[column] > right)]
    
    print(f'Количество выбросов в столбце {column}: {len(outliers)}')
    print(f'Границы нормы: {max(round(left, 2), 0)} - {round(right, 2)}')

    if not outliers.empty:
        display(outliers[['job_title', 'experience_level', 'education_required', 'company_size', column]])

    return outliers

In [77]:
outliers_yoe = get_outliers(df_jobs, 'years_of_experience')

Количество выбросов в столбце years_of_experience: 5
Границы нормы: 0 - 14.0

,job_title,experience_level,education_required,company_size,years_of_experience
13,AI Solutions Architect,Entry (0-2 yrs),Bootcamp/Self-taught,Startup (1-50),15
170,AI Solutions Architect,Entry (0-2 yrs),Associate's,Enterprise (5000+),15
291,AI Solutions Architect,Mid (3-5 yrs),Associate's,SME (51-500),15
319,AI Solutions Architect,Entry (0-2 yrs),Master's,Startup (1-50),15
1284,AI Solutions Architect,Entry (0-2 yrs),Bootcamp/Self-taught,Enterprise (5000+),15

Выбросы по столбцу years_of_experience (стаж) со значением 15 лет противоречат данным столбца experience_level с опытом Entry или Mid. Принято решение удалить соответствующие строки, чтобы не искажать статистику для начинающих специалистов.

In [78]:
df_jobs = df_jobs.drop(outliers_yoe.index)

In [79]:
outliers_an_sal = get_outliers(df_jobs, 'annual_salary_usd')

Количество выбросов в столбце annual_salary_usd: 3
Границы нормы: 4500.0 - 376500.0

,job_title,experience_level,education_required,company_size,annual_salary_usd
822,AI Solutions Architect,Lead (10+ yrs),PhD,Big Tech (FAANG+),384000.0
896,AI Solutions Architect,Lead (10+ yrs),PhD,Big Tech (FAANG+),384000.0
1374,AI Solutions Architect,Lead (10+ yrs),Master's,SME (51-500),384000.0

По столбцу annual_salary_usd было выявлено 3 статистических выброса. Однако это валидные данные для позиций уровня Lead в BigTech или SME со степенью Phd или Master. Сохраним данные, чтобы не терять информацию о верхнем сегменте рынка.

In [80]:
outliers_sal_min = get_outliers(df_jobs, 'salary_min_usd')

Количество выбросов в столбце salary_min_usd: 0
Границы нормы: 67500.0 - 207500.0

In [81]:
outliers_sal_max = get_outliers(df_jobs, 'salary_max_usd')

Количество выбросов в столбце salary_max_usd: 0
Границы нормы: 110000.0 - 398000.0

In [82]:
outliers_sal_premium = get_outliers(df_jobs, 'ai_salary_premium_pct')

Количество выбросов в столбце ai_salary_premium_pct: 0
Границы нормы: 0 - 23.2

В числовых столбцах salary_min_usd, salary_max_usd, ai_salary_premium_pct выбросов не обнаружено.

Также проверим, чтобы salary_min_usd везде был меньше или равен salary_max_usd.

In [83]:
wrong_salaries = df_jobs[df_jobs['salary_min_usd'] > df_jobs['salary_max_usd']]

print(f'Количество строк с ошибкой в вилке зарплат: {len(wrong_salaries)}')

Количество строк с ошибкой в вилке зарплат: 0

Проверим, чтобы значения столбцов demand_score (0-100) и benefits_score_10 (0-10) находились в допустимых диапазонах.

In [84]:
print(f'Минимум demand_score: {df_jobs['demand_score'].min()}')
print(f'Максимум demand_score: {df_jobs['demand_score'].max()}')
print(f'Минимум benefits_score_10: {df_jobs['benefits_score_10'].min()}')
print(f'Максимум benefits_score_10: {df_jobs['benefits_score_10'].max()}')

Минимум demand_score: 68
Максимум demand_score: 98
Минимум benefits_score_10: 6.0
Максимум benefits_score_10: 9.8

Значения столбцов demand_score (0-100) и benefits_score_10 (0-10) находятся в допустимых диапазонах.

In [85]:
outliers_demand_growth = get_outliers(df_jobs, 'demand_growth_yoy_pct')

Количество выбросов в столбце demand_growth_yoy_pct: 29
Границы нормы: 0 - 83.78

,job_title,experience_level,education_required,company_size,demand_growth_yoy_pct
96,LLM Engineer,Senior (6-9 yrs),Bachelor's,Big Tech (FAANG+),84.6
192,LLM Engineer,Senior (6-9 yrs),Bachelor's,Big Tech (FAANG+),85.9
196,Generative AI Engineer,Lead (10+ yrs),Associate's,SME (51-500),87.6
204,AI Engineer,Mid (3-5 yrs),Associate's,Startup (1-50),85.8
236,Generative AI Engineer,Entry (0-2 yrs),Associate's,Enterprise (5000+),87.8
268,RAG Engineer,Entry (0-2 yrs),Bootcamp/Self-taught,SME (51-500),86.1
279,LLM Engineer,Senior (6-9 yrs),Master's,Enterprise (5000+),84.8
294,Generative AI Engineer,Lead (10+ yrs),Master's,SME (51-500),86.2
311,Data Scientist,Entry (0-2 yrs),PhD,Big Tech (FAANG+),84.7
364,Senior ML Engineer,Lead (10+ yrs),Master's,Startup (1-50),87.7
492,RAG Engineer,Senior (6-9 yrs),Bootcamp/Self-taught,Enterprise (5000+),87.5
532,Senior ML Engineer,Senior (6-9 yrs),Associate's,SME (51-500),86.2
616,NLP Engineer,Lead (10+ yrs),PhD,Startup (1-50),87.1
722,Senior ML Engineer,Senior (6-9 yrs),Bootcamp/Self-taught,Enterprise (5000+),84.6
771,Generative AI Engineer,Mid (3-5 yrs),PhD,Mid-size (501-5000),85.1
774,AI Agent Developer,Mid (3-5 yrs),Master's,Enterprise (5000+),85.2
801,RAG Engineer,Lead (10+ yrs),Bachelor's,Mid-size (501-5000),87.6
843,Senior ML Engineer,Lead (10+ yrs),Bachelor's,Big Tech (FAANG+),83.9
867,LLM Engineer,Entry (0-2 yrs),Associate's,Startup (1-50),86.2
1054,Generative AI Engineer,Lead (10+ yrs),Bachelor's,Mid-size (501-5000),83.9
1086,ML Engineer,Lead (10+ yrs),PhD,SME (51-500),84.0
1136,RAG Engineer,Entry (0-2 yrs),Master's,Mid-size (501-5000),85.0
1218,AI Agent Developer,Entry (0-2 yrs),Bootcamp/Self-taught,Mid-size (501-5000),84.0
1247,AI Agent Developer,Entry (0-2 yrs),Bootcamp/Self-taught,Big Tech (FAANG+),86.1
1278,AI Engineer,Entry (0-2 yrs),Bootcamp/Self-taught,Startup (1-50),87.3
1389,MLOps Engineer,Entry (0-2 yrs),Master's,Big Tech (FAANG+),85.2
1398,LLM Engineer,Mid (3-5 yrs),Master's,SME (51-500),85.5
1415,MLOps Engineer,Entry (0-2 yrs),Master's,SME (51-500),83.8
1426,NLP Engineer,Senior (6-9 yrs),Associate's,Startup (1-50),85.2

По столбцу demand_growth_yoy_pct выявлено 29 статистических выбросов. Однако эти строки относятся к передовым направлениям, таким как LLM, NLP, RAG, Generative AI, где наблюдается высокий спрос. Для сохранения репрезентативности рынка следует оставить данные строки.

Проверим остальные числовые столбцы на логику.

In [86]:
print(f'Уникальные значения is_senior: {", ".join(map(str, sorted(df_jobs['is_senior'].unique())))}')
print(f'Уникальные значения is_remote_friendly: {", ".join(map(str, sorted(df_jobs['is_remote_friendly'].unique())))}')
print(f'Уникальные значения is_llm_role: {", ".join(map(str, sorted(df_jobs['is_llm_role'].unique())))}')

Уникальные значения is_senior: 0, 1
Уникальные значения is_remote_friendly: 0, 1
Уникальные значения is_llm_role: 0, 1

Бинарные признаки принимают значения 0 и 1. Следовательно, они закодированы верно.

In [87]:
print(f'Уникальные значения posting_year: {", ".join(map(str, sorted(df_jobs['posting_year'].unique())))}')
print(f'Уникальные значения posting_month: {", ".join(map(str, sorted(df_jobs['posting_month'].unique())))}')

Уникальные значения posting_year: 2025, 2026
Уникальные значения posting_month: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12

Значения года и месяца находятся в допустимом диапазоне.

При просмотре датасета было обнаружено, что требуемый опыт работы в годах (years_of_experience) не всегда соответствует заявленной категории опыта (experience_level). 

Проверим соответствие признаков years_of_experience и experience_level.

Для начала выведем все возможные категории experience_level.

In [88]:
df_jobs['experience_level'].unique()

<StringArray>
['Senior (6-9 yrs)', 'Lead (10+ yrs)', 'Entry (0-2 yrs)', 'Mid (3-5 yrs)']
Length: 4, dtype: str

Теперь проверим, в скольких строках опыт в годах не соответствует указанной категории.

In [93]:
entry_mismatch = df_jobs[(df_jobs['experience_level'] == 'Entry (0-2 yrs)') & (df_jobs['years_of_experience'] > 2)]
mid_mismatch = df_jobs[(df_jobs['experience_level'] == 'Mid (3-5 yrs)') & ((df_jobs['years_of_experience'] < 3) | (df_jobs['years_of_experience'] > 5))]
senior_mismatch = df_jobs[(df_jobs['experience_level'] == 'Senior (6-9 yrs)') & ((df_jobs['years_of_experience'] < 6) | (df_jobs['years_of_experience'] > 9))]
lead_mismatch = df_jobs[(df_jobs['experience_level'] == 'Lead (10+ yrs)') & (df_jobs['years_of_experience'] < 10)]


print(f"Несоответствий в категории Entry: {len(entry_mismatch)}")
print(f"Несоответствий в категории Mid: {len(mid_mismatch)}")
print(f"Несоответствий в категории Mid: {len(senior_mismatch)}")
print(f"Несоответствий в категории Lead: {len(lead_mismatch)}")

Несоответствий в категории Entry: 341
Несоответствий в категории Mid: 234
Несоответствий в категории Mid: 183
Несоответствий в категории Lead: 336

Поскольку несоответствий очень много, эти строки нельзя удалять.

Попробуем разобраться, какой из признаков реально соответствует заявленной позиции. 

Для этого сгруппируем по категории опыта и для каждой найдем минимум, максимум, среднее и медиану стажа (years_of_experience).

In [ ]:
df_jobs.groupby('experience_level')['years_of_experience'].agg(['min', 'max', 'mean', 'median'])

                  min  max      mean  median
experience_level
Entry (0-2 yrs)     1   14  6.070866     6.0
Lead (10+ yrs)      1   14  6.144357     6.0
Mid (3-5 yrs)       1   13  6.208672     6.0
Senior (6-9 yrs)    1   12  6.329670     6.0

Группировка показала, что значения среди категорий практически одинаковы. Это говорит о том, что столбец years_of_experience заполнен некорректно либо случайным образом.

Также вычислим корреляцию years_of_experience с annual_salary_usd. Если значения признака years_of_experience корректны, корреляция должна быть высокой, поскольку с ростом опыта, как правило, растет и заработная плата.

In [95]:
df_jobs[['years_of_experience', 'annual_salary_usd']].corr()

                     years_of_experience  annual_salary_usd
years_of_experience             1.000000           0.082411
annual_salary_usd               0.082411           1.000000

Корреляция между years_of_experience и annual_salary_usd близка нулю. Взаимосвязь практически отсутствует, что указывает на то, что значения years_of_experience некорректны.

Рассчитаем среднюю зарплату для каждой категории опыта, чтобы убедиться, что значения в признаке experience_level корректны. Чем больше опыт, тем выше должна быть средняя зарплата.

In [97]:
df_jobs.groupby('experience_level')['annual_salary_usd'].mean().sort_values()

experience_level
Entry (0-2 yrs)     149708.661417
Mid (3-5 yrs)       175972.899729
Senior (6-9 yrs)    214280.219780
Lead (10+ yrs)      240055.118110
Name: annual_salary_usd, dtype: float64

Средняя зарплата растет с опытом. Следовательно, можно исходить из того, что значения признака experience_level корректны. Поэтому в дальнейшем в качестве опыта будет использоваться только признак experience_level.

Столбец years_of_experience останется без внимания, поскольку это ненадежный признак. Первичный анализ выявил выбросы со стажем 15 лет. Однако дальнейший анализ показал всю несогласованность столбца years_of_experience с категориями опыта. В связи с этим принято решение исключить этот признак из дальнейшей разработки сервиса.

Далее проверим соответствие зарплаты (annual_salary_usd) категориям зарплаты (salary_tier).

In [99]:
df_jobs['salary_tier'].unique()

<StringArray>
[   'Senior ($200-300k)', 'Upper-Mid ($150-200k)',        'Elite (>$300k)',
       'Mid ($100-150k)',        'Entry (<$100k)']
Length: 5, dtype: str

In [100]:
entry_sal_mismatch = df_jobs[(df_jobs['salary_tier'] == 'Entry (<$100k)') & (df_jobs['annual_salary_usd'] > 100000)]
mid_sal_mismatch = df_jobs[(df_jobs['salary_tier'] == 'Mid ($100-150k)') & ((df_jobs['annual_salary_usd'] < 100000) | (df_jobs['annual_salary_usd'] > 150000))]
upper_mid_sal_mismatch = df_jobs[(df_jobs['salary_tier'] == 'Upper-Mid ($150-200k)') & ((df_jobs['annual_salary_usd'] < 150000) | (df_jobs['annual_salary_usd'] > 200000))]
senior_sal_mismatch = df_jobs[(df_jobs['salary_tier'] == 'Senior ($200-300k)') & ((df_jobs['annual_salary_usd'] < 200000) | (df_jobs['annual_salary_usd'] > 300000))]
elite_sal_mismatch = df_jobs[(df_jobs['salary_tier'] == 'Elite (>$300k)') & (df_jobs['annual_salary_usd'] < 300000)]


print(f"Несоответствий в категории Entry: {len(entry_sal_mismatch)}")
print(f"Несоответствий в категории Mid: {len(mid_sal_mismatch)}")
print(f"Несоответствий в категории Mid: {len(upper_mid_sal_mismatch)}")
print(f"Несоответствий в категории Lead: {len(senior_sal_mismatch)}")
print(f"Несоответствий в категории Lead: {len(elite_sal_mismatch)}")

Несоответствий в категории Entry: 0
Несоответствий в категории Mid: 0
Несоответствий в категории Mid: 0
Несоответствий в категории Lead: 0
Несоответствий в категории Lead: 0

В числовом признаке зарплаты (annual_salary_usd) и категории зарплаты (salary_tier) расхождений не наблюдается.

Превратим строки в столбце required_skills в списки по разделителю '|', чтобы упростить дальнейшую работу с данным признаком.

In [101]:
df_jobs['required_skills'] = df_jobs['required_skills'].str.strip().str.split(r'\s*\|\s*')
df_jobs.head(3)

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,country,remote_work,company_size,industry,required_skills,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000.0,155000,290000,Boston,USA,On-site,Startup (1-50),Finance,"[APIs, Planning Systems, Python, Cloud, SQL, L...",13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2,Bachelor's,166000.0,90000,200000,London,UK,Hybrid,Enterprise (5000+),Finance,"[Python, Documentation, LLM APIs, Prompt Desig...",5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k)
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4,Associate's,360000.0,160000,300000,Seattle,USA,Fully Remote,Big Tech (FAANG+),Finance,"[Vector DBs, Python, Prompt Engineering, Fine-...",9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k)

Создадим признак number_of_required_skills для дальнейшей фильтрации и анализа зависимостей.

In [103]:
df_jobs['number_of_required_skills'] = df_jobs['required_skills'].apply(len)

In [104]:
df_jobs.head(3)

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,country,remote_work,company_size,industry,required_skills,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier,number_of_required_skills
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000.0,155000,290000,Boston,USA,On-site,Startup (1-50),Finance,"[APIs, Planning Systems, Python, Cloud, SQL, L...",13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k),6
1,AIJOB0002,Prompt Engineer,AI Engineering,Senior (6-9 yrs),2,Bachelor's,166000.0,90000,200000,London,UK,Hybrid,Enterprise (5000+),Finance,"[Python, Documentation, LLM APIs, Prompt Desig...",5.4,82,11.6,6.2,2026,1,1,1,1,Upper-Mid ($150-200k),7
2,AIJOB0003,LLM Engineer,AI Engineering,Senior (6-9 yrs),4,Associate's,360000.0,160000,300000,Seattle,USA,Fully Remote,Big Tech (FAANG+),Finance,"[Vector DBs, Python, Prompt Engineering, Fine-...",9.1,98,42.7,7.7,2026,1,1,1,1,Elite (>$300k),5

Выведем уникальные значения категориальных признаков job_category, experience_level, industry, company_size, remote_work, которые станут фильтрами в сервисе, чтобы исключить вероятность ошибок/опечаток и понять масштабы.

In [109]:
categorial_cols = ['job_category', 'experience_level', 'industry', 'company_size', 'remote_work']

for col in categorial_cols:
    unique_values = ', '.join(sorted(df_jobs[col].unique()))
    print(f"{col} ({len(df_jobs[col].unique())} знач.): {unique_values}\n")

job_category (12 знач.): AI Engineering, Architecture, Business, Data Engineering, Data Science, Governance, Infrastructure, ML Operations, Product, Research, Robotics, Security

experience_level (4 знач.): Entry (0-2 yrs), Lead (10+ yrs), Mid (3-5 yrs), Senior (6-9 yrs)

industry (12 знач.): Automotive, Consulting, Education, Energy, Finance, Government, Healthcare, Manufacturing, Media, Research, Retail, Technology

company_size (5 знач.): Big Tech (FAANG+), Enterprise (5000+), Mid-size (501-5000), SME (51-500), Startup (1-50)

remote_work (3 знач.): Fully Remote, Hybrid, On-site

Выведем уникальные города, чтобы проверить написание названий городов в обоих датасетах для правильного объединения.

In [114]:
unique_cities = sorted(df_jobs['city'].unique())
print(f'Уникальных городов в df_jobs: {len(unique_cities)}')
unique_cities

Уникальных городов в df_jobs: 20

['Amsterdam',
 'Austin',
 'Bangalore',
 'Beijing',
 'Berlin',
 'Boston',
 'Chicago',
 'Dubai',
 'London',
 'Los Angeles',
 'New York',
 'Paris',
 'Remote',
 'San Francisco',
 'Seattle',
 'Singapore',
 'Sydney',
 'Tokyo',
 'Toronto',
 'Zurich']

В списке городов также находится значение Remote (удаленно) не относящееся ни к какому городу. Проверим, сколько таких записей в датасете, чтобы понимать какое количество строк не получится соединить со вторым датасетом, хранящим информацию о стоимости жизни в разных городах.

In [120]:
print(f'Доля строк со значением Remote в столбце city: {round(len(df_jobs[df_jobs['city'] == 'Remote']) / len(df_jobs), 2)}')

Доля строк со значением Remote в столбце city: 0.05

Таких строк около 5 %. Поэтому потеря информации будет небольшая.